name: ci
on:
  push:
    paths-ignore:
      - "**.md"
      - LICENCE
    branches:
  pull_request:
env:
  DEFAULT_GO_VERSION: 1.15
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ env.DEFAULT_GO_VERSION }}
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run test
        run: go test ./...
      - name: Build
        run: go build
      - name: Build Examples
        run: |
          # build basic example
          docker build -f ./examples/basic/Dockerfile .

          # build multi services example
          docker build -f ./examples/multi-services/back-svc/Dockerfile ./examples/multi-services
          docker build -f ./examples/multi-services/front-svc/Dockerfile ./examples/multi-services
